---
title: "Visulizaiton"
author: "Franky Zhang, Ranfei Xu, Biyao Zhang"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.width=6)#, fig.height= 4, fig.width=8
pacman::p_load("magrittr","dplyr","plotrix","tidyverse","ggplot2","gridExtra","viridis","hrbrthemes","reshape2","ggrepel","grid")
```

# data cleaning

```{r}
# read data
data <- readxl::read_xlsx("dt_EDA_0301.xlsx", col_names  = TRUE)[-1 , ]

# change col name
colnames(data)[which(names(data) == "Q39")] <- "first"
colnames(data)[which(names(data) == "Q37_fixed")] <- "race"
colnames(data)[which(names(data) == "Q35")] <- "age"


# give meaning to the value of obs.
data$race <- str_replace_all(data$race, c("1" = "African American", "2" = "Asian/Pacific Islander", "3" = "Caucasian/White", "4" = "Hispanic/Latinx", "5" = "Native American/Alaskan Native", "6" = "Multi-Racial", "7" = "Other"))
data$age <- str_replace_all(data$age, c("1" = "A", "2" = "B", "3" = "C", "4" = "D"))
data$age <- str_replace_all(data$age, c("A" = "18-24", "B" = "25-31", "C" = "32-38", "D" = "39+"))


challenges.names <- c()
for (i in 1:9) {
  challenges.names[i] <- paste("33", letters[i], sep = "_")
}
application.challenges <-  c("shadowing", "crisis counseling", 
                             "advocacy", "teaching/mentoring", 
                             "talking with genetic counselors", 
                             "finding out information", 
                             "cost", "prerequisite classes", "other")
challenges <- data %>% dplyr::select(challenges.names)
GC_related_experience <- data$Q12
for (i in 1: length(GC_related_experience)) {
  GC_related_experience[i] <- ifelse(GC_related_experience[i] == "1", 
                                     "yes", "no")
}


```



# demo ~ application

```{r}

#Schhols,gap years~application !!!
data1<-select(data,Q7,Q8,age)
#A<-filter(data1,Q35=="A")
data1$Q7 <- as.numeric(data1$Q7)
data1$Q8 <- as.numeric(data1$Q8)
# which(is.na(data1$Q8))
data1 <- data1[-which(data1$age == "NA"), ]
data1 <- data1[-which(is.na(data1$Q8)), ]
data1 %>% group_by(age) %>%
  summarise(freq_Q8 = mean(Q8), freq_Q7 = mean(Q7))
# create a dataset
age <- c(rep("18-24" , 2) , rep("25-31" , 2) , rep("32-38" , 2) , rep("39+" , 2) )
condition <- rep(c("Schools" , "Gap Years") , 4)
value <- c(4.71,3.16,1.59,1,1.17,0.5,0.176,18)
d <- data.frame(age,condition,value)
# Grouped
ggplot(d, aes(fill=condition, y=value, x=age)) + 
  geom_bar(position="dodge", stat="identity",aes())+theme_ipsum()

#Racw~application Q37 !!!
data2<-select(data,Q7,Q8,race)
data2$Q7 <- as.numeric(data2$Q7)
data2$Q8 <- as.numeric(data2$Q8)
data2 <- data2[-which(is.na(data2$Q8)), ]
data2 <- data2[-which(data2$race == "NA"), ]
data2 %>% group_by(race) %>%
    summarise(freq_Q8 = mean(Q8), freq_Q7 = mean(Q7))
data2$race<-str_replace_all(data2$race,c("1"="African American","2"="Asian/Pacific","3"="Caucaisian/White","4"="Hispanic/Latinx","5"="Native American/Alaskan Native","6"="Multi-racial","7"="Other"))

race <- c(rep("African American" , 2) , rep("Asian/Pacific" , 2) , rep("Caucaisian/White" , 2),rep("Hispanic/Latinx" , 2),rep("Native American/Alaskan Native" , 2),rep("Multi-racial" , 2),rep("Other", 2))
condition <- rep(c("Schools" , "Gap Years") , 7)
value <- c(6.2,5.36,3.62,2.43,6,2,2.5,1.8,1.79,0.802,1.14,1.42,1,0.5)
d <- data.frame(race,condition,value)
# Grouped
ggplot(d, aes(fill=condition, y=value, x=race)) + 
  geom_bar(position="dodge", stat="identity",aes())+theme_ipsum()

# First generation~Application Q39
data3<-select(data,Q7,Q8,first)
data3$Q7 <- as.numeric(data3$Q7)
data3$Q8 <- as.numeric(data3$Q8)
data3<- data3[-which(is.na(data3$Q8)), ]
data3<- data3[-which(data3$first == "NA"), ]
data3 %>% group_by(first) %>%
  summarise(freq_Q8 = mean(Q8), freq_Q7 = mean(Q7))
data3$first<-str_replace_all(data3$first,c("0"="Yes","1"="No"))

Generation <- c(rep("First Generation" , 2) , rep("Not First Generation" , 2))
condition <- rep(c("Schools" , "Gap Years") , 2)
value <- c(4.48,2.75,1.08,0.720)
d <- data.frame(Generation,condition,value)
# Grouped
ggplot(d, aes(fill=condition, y=value, x=Generation)) + 
  geom_bar(position="dodge", stat="identity",aes())+theme_ipsum()

```

```{r}
table(GC_related_experience) # 115 have experience while 77 have no experience 
# which is not an extreme ratio
challenge.data <- 
  cbind(GC_related_experience, challenges)[-which(is.na(GC_related_experience)), ] # Q12
# challenge.data <- cbind(GC_related_experience, challenges)
rm(challenges, GC_related_experience)
challenge.data[challenge.data == "NA"] <- 0
# numerical the data
challenge.data$`33_a` <- as.numeric(challenge.data$`33_a`)
challenge.data$`33_b` <- as.numeric(challenge.data$`33_b`)
challenge.data$`33_c` <- as.numeric(challenge.data$`33_c`)
challenge.data$`33_d` <- as.numeric(challenge.data$`33_d`)
challenge.data$`33_e` <- as.numeric(challenge.data$`33_e`)
challenge.data$`33_f` <- as.numeric(challenge.data$`33_f`)
challenge.data$`33_g` <- as.numeric(challenge.data$`33_g`)
challenge.data$`33_h` <- as.numeric(challenge.data$`33_h`)
challenge.data$`33_i` <- as.numeric(challenge.data$`33_i`)

# separate data
challenge.data.1 <- challenge.data %>% filter(GC_related_experience == "yes") %>% 
  select(challenges.names)
challenge.data.2 <- challenge.data %>% filter(GC_related_experience == "no")  %>% 
  select(challenges.names)
compare.expereience <- data.frame(rbind(apply(challenge.data.1, 2, sum), 
                                        apply(challenge.data.2, 2, sum)))
rownames(compare.expereience) <- c("with experience", "without experience")
colnames(compare.expereience) <- application.challenges
rm(challenge.data.1, challenge.data.2)
```


```{r}
with_experience <- c()
without_experience <- c()

for (i in 1:ncol(compare.expereience)) {
  with_experience[i] <- compare.expereience[1, i]
  without_experience[i] <- compare.expereience[2, i]
}
library(RColorBrewer)
# with GC-related experience
myPalette <- brewer.pal(9, "Pastel1")
slice_labels <- round(with_experience/sum(with_experience)*100, 1)
slice_labels <- paste(slice_labels, "%", sep = "")
pie(with_experience, labels = slice_labels, border = "black", 
      col = myPalette, main = "with GC-related experience")
legend("topright", application.challenges, cex=0.6, fill=myPalette)

# without GC-related experience

slice_labels <- round(without_experience/sum(without_experience)*100, 1)
slice_labels <- paste(slice_labels, "%", sep = "")
pie(without_experience, labels = slice_labels, border = "black", 
      col = myPalette, main = "without GC-related experience")
legend("topright", application.challenges, cex=0.6, fill=myPalette)
```

# demo ~ challenges

```{r}
dt <- data
oldnames = c("33_a",	"33_b",	"33_c",	"33_d",	"33_e",	"33_f",	"33_g",	"33_h",	"33_i")
dt <- dt %>% rename_at(vars(oldnames), ~ application.challenges)
dt <- dt[,c(10:17,19,21,26,27)] # 217 obs.
dt <- na.omit(dt) # 179 obs.
```

### race ~ challenges

```{r}
# prepare data
dt_race <- melt(dt[,-c(9,11,12)],id.vars=c("race"))%>%na.omit()
dt_race$value <- as.numeric(dt_race$value)
dt4EDA_race <- dt_race%>% 
  group_by(race, variable) %>%  summarise(true=sum(value),count = n())%>%
  mutate(value = round(true /count,2)) 

# plot
ggplot(dt4EDA_race, aes(fill = variable, y = value, x = race)) + 
    geom_bar(position="stack", stat="identity")+
    scale_fill_brewer(palette = "Set3") +
    ggtitle("Race ~ Chanllenges") +
    xlab("Race")+
    ylab("The Average # Challenges")+
    scale_fill_discrete(name = "Challenges")+
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
    theme_minimal()
ggsave("race_challenge.png")
dt_race%>% 
  group_by(race) %>%
  summarise(count = n())%>%
  ggplot(aes(x="Race", y=count, fill=race))+
  geom_bar(width = 1, stat = "identity")+
  scale_fill_brewer(palette = "Pastel2") +
  coord_polar("y", start=0) +
  geom_label_repel(aes(label = paste0(round(count/nrow(dt_race),2), "%")),
                   size = 4.5,  show.legend = FALSE) +
  guides(fill = guide_legend(title = "Group")) +
  theme_void() #  theme_minimal()
ggsave("race.png")
```

### age ~ challenges

```{R}
# prepare data
dt_age <- melt(dt[,-c(10,11,12)],id.vars=c("age")) %>% na.omit()
dt_age$value <- as.numeric(dt_age$value)
dt4EDA_age <- dt_age%>% 
  group_by(age, variable) %>%
  summarise(true=sum(value),count = n())%>% 
  # `summarise()` has grouped output by 'age'. You can override using the `.groups` argument. ???
  mutate(value = round(true /count,2)) 
# plot
ggplot(dt4EDA_age, aes(fill = variable, y = value, x = age)) + 
    geom_bar(position="stack", stat="identity")+
    scale_fill_brewer(palette = "Set3") +
    ggtitle("Age ~ Challenges") +
    xlab("Age")+
    ylab("The Average # Challenges")+
    scale_fill_discrete(name = "Challenges")+
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))+
    theme_minimal()
    
ggsave("age_challenge.png")
dt_age%>% 
  group_by(age) %>%
  summarise(count = n())%>%
  ggplot(aes(x="Age", y=count, fill=age))+
  geom_bar(width = 1, stat = "identity")+
  scale_fill_brewer(palette = "Pastel2") +
  coord_polar("y", start=0) +
  geom_label_repel(aes(label = paste0(round(count/nrow(dt_age),2), "%")),
                   size = 4.5,  show.legend = FALSE) +
  guides(fill = guide_legend(title = "Group")) +
  theme_void() #  theme_minimal()
  
ggsave("age.png")
```

### first generation ~ challenge
```{R}
# prepare data
dt_first <- melt(dt[,-c(9,10,12)],id.vars=c("first"))
dt_first$value <- as.numeric(dt_first$value)
dt_first$first <- as.factor(dt_first$first)
dt4EDA_first <- dt_first%>% 
  group_by(first, variable) %>%
  summarise(true=sum(value),count = n())%>%
  mutate(value = round(true / count,2))

# plot
ggplot(dt4EDA_first, aes(fill = variable, y = value, x = first)) + 
    geom_bar(position="stack", stat="identity")+
    scale_fill_brewer(palette = "Set3") +
    ggtitle("1st Generation ~ Challenges") +
    xlab("1st Generation")+
    ylab("The Average # Challenges")+
    scale_fill_discrete(name = "Challenges")+
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))+
    theme_minimal()
ggsave("first_challenge.png")

dt_first%>% 
  group_by(first) %>%
  summarise(count = n())%>%
  ggplot(aes(x="1st generation", y=count, fill=first))+
  geom_bar(width = 1, stat = "identity")+
  scale_fill_brewer(palette = "Pastel2") +
  coord_polar("y", start=0) +
  geom_label_repel(aes(label = paste0(round(count/nrow(dt_first),2), "%")),
                   size = 4.5,  show.legend = FALSE) +
  guides(fill = guide_legend(title = "Group")) +
  theme_void() #  theme_minimal()
ggsave("first.png")
```
